<?php
    include_once(DIR_FS_CLASSES."users.class.php");
    include_once(DIR_FS_CLASSES."admin.class.php");
    include_once(DIR_FS_CLASSES."manage_broker.class.php");
    include_once(DIR_FS_CLASSES."manage_account.class.php");
    include_once(DIR_FS_CLASSES."manage_product.class.php");
    include_once(DIR_FS_CLASSES."manage_payroll.class.php");
    include_once(DIR_FS_CLASSES."client_suitebility.class.php");
    include_once(DIR_FS_CLASSES."client_maintenance.class.php");
    include_once(DIR_FS_CLASSES."product_maintenance.class.php");
    include_once(DIR_FS_CLASSES."system_configuration.class.php");
    include_once(DIR_FS_CLASSES."date_interfaces.class.php");
    include_once(DIR_FS_CLASSES."manage_company.class.php");
    include_once(DIR_FS_CLASSES."manage_sponsor.class.php");
    include_once(DIR_FS_CLASSES."branch_maintenance.class.php");
    include_once(DIR_FS_CLASSES."batches.class.php");
    include_once(DIR_FS_CLASSES."import.class.php");
	include_once(DIR_FS_CLASSES."header.class.php");
    include_once(DIR_FS_CLASSES."transaction.class.php");
    include_once(DIR_FS_CLASSES."broker_document.class.php");
    include_once(DIR_FS_CLASSES."ofac_fincen.class.php");
    include_once(DIR_FS_CLASSES."rules_engine.class.php");
    include_once(DIR_FS_CLASSES."client_ress.class.php");
    include_once(DIR_FS_CLASSES."home.class.php");
    include_once(DIR_FS_CLASSES."payout_schedule_master.class.php");
    include_once(DIR_FS_CLASSES."payroll.class.php");
?>